image: cpro29a/go-ci-image

stages:
    - lint
    - test
    - docker
    - deploy

lint:
    stage: lint
    script: golangci-lint run

test:
    stage: test
    image: docker
    services:
        - docker:dind
    variables:
        POSTGRESCONNSTR: postgres://wallet:wallet@postgres:5432/wallet?sslmode=disable
    script:
        - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
        - pip install docker-compose
        - docker-compose up -d postgres
        - docker build -t testimage -f Dockerfile.test .
        - docker run --rm testimage
    after_script:
        - docker-compose down
        - docker rmi -f testimage

docker:
    image: docker
    services:
        - docker:dind
    stage: docker
    script:
        - docker build -t $CI_REGISTRY_IMAGE:latest .
        - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE:latest
