image: cpro29a/go-ci-image

stages:
    - lint
    - test
    - docker
    - deploy

lint:
    stage: lint
    script: golangci-lint run

test:
    stage: test
    image: cpro29a/docker-compose-golang
    services:
        - docker:dind
    variables:
        POSTGRESCONNSTR: postgres://wallet:wallet@postgres:5432/wallet?sslmode=disable
        DOCKER_HOST: tcp://docker:2375/
    script:
        - docker-compose up -d postgres
        - docker build -t testimage -f Dockerfile.test .
        - docker run -e POSTGRESCONNSTR --rm --network=wallet-test_default testimage
    after_script:
        - docker-compose down
        - docker rmi -f testimage

docker:
    image: docker
    services:
        - docker:dind
    stage: docker
    script:
        - docker build -t $CI_REGISTRY_IMAGE:latest .
        - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE:latest
