version: "2"

services:
    postgres:
        image: postgres:11-alpine
        volumes:
            - $PWD/sql:/docker-entrypoint-initdb.d/

    wallet:
        environment:
            - POSTGRESCONNSTR=postgres://wallet:wallet@postgres:5432/wallet?sslmode=disable
        build: .
        ports:
            - 8080:8080
        depends_on:
            - postgres
