version: "3"

services:
  postgtres:
    image: postgres:11-alpine
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d/

  wallet:
    image: gitlab.com/c-pro/wallet-test
    ports:
      - 8080:8080
    environment:
        - POSTGRESCONNSTR=postgres://wallet:wallet@postgres:5432/wallet?sslmode=disable
    deploy:
      replicas: 4
