version: "3"

services:
  postgtres:
    image: postgres:12-beta1-alpine
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d/

  wallet:
    build: .
    ports:
      - 8080:8080
    deploy:
      replicas: 4
      restart-policy:
        condition: on-failure
